site_name: Knowledge Base Platform
site_url: https://vincentbenzo.github.io/kb-platform/
repo_url: https://github.com/vincentbenzo/kb-platform
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: theme/overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    # Dark mode (primary option)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Light mode (secondary option)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/book-open-page-variant

extra_css:
  - theme/assets/stylesheets/extra.css

extra_javascript:
  - theme/javascripts/workspace-selector.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

nav:
  - Home: index.md