name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Debug file structure
        run: |
          echo "Listing theme directory:"
          ls -la theme/
          echo "Listing theme assets directory:"
          ls -la theme/assets/
          echo "Checking if CSS file exists:"
          ls -la theme/assets/stylesheets/
      
      - name: Ensure CSS is available
        run: |
          mkdir -p site/theme/assets/stylesheets/
          # Copy CSS to ensure it's available
          cp theme/assets/stylesheets/extra.css site/theme/assets/stylesheets/
          
      - name: Build main platform
        run: mkdocs build
        
      - name: Verify build output
        run: |
          echo "Checking if CSS was copied to site:"
          ls -la site/theme/assets/stylesheets/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true